server {
    listen 80;
    server_name new.meme.skyfly.hackclub.app localhost;

    root /usr/share/nginx/html;
    index index.html;

    types {
        text/html                             html htm;
        text/css                              css;
        text/javascript                       js mjs;
        application/json                      json;
        image/png                             png;
        image/jpeg                            jpg jpeg;
        image/svg+xml                         svg;
        image/x-icon                          ico;
        font/woff2                            woff2;
    }

    gzip on;
    gzip_static on;
    gzip_types text/plain text/css application/json application/javascript text/javascript image/svg+xml;
    gzip_min_length 1000;

    location / {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        try_files $uri $uri/ /index.html;
    }

    location ~* \.map$ {
        return 404;
    }

    location ~* \.(js|mjs|css)$ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location ~* \.(png|jpg|jpeg|gif|ico|svg|woff2)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
